-- *** BBDD 04_tienda ***
-- Devuelve una lista con el nombre del producto, precio y nombre de fabricante de todos los productos de la base de datos.
-- Devuelve una lista con el nombre del producto, precio y nombre de fabricante de todos los productos de la base de datos. Ordene el resultado por el nombre del fabricante, por orden alfabético.
-- Devuelve una lista con el código del producto, nombre del producto, código del fabricante y nombre del fabricante, de todos los productos de la base de datos.
-- Devuelve el nombre del producto, su precio y el nombre de su fabricante, del producto más barato.
-- Devuelve el nombre del producto, su precio y el nombre de su fabricante, del producto más caro.
-- Devuelve una lista de todos los productos del fabricante Lenovo.
-- Devuelve una lista de todos los productos del fabricante Crucial que tengan un precio mayor que 200€.
-- Devuelve un listado con todos los productos de los fabricantes Asus, Hewlett-Packardy Seagate. Sin utilizar el operador IN.
-- Devuelve un listado con todos los productos de los fabricantes Asus, Hewlett-Packardy Seagate. Utilizando el operador IN.
-- Devuelve un listado con el nombre y el precio de todos los productos de los fabricantes cuyo nombre termine por la vocal e.
-- Devuelve un listado con el nombre y el precio de todos los productos cuyo nombre de fabricante contenga el carácter w en su nombre.
-- Devuelve un listado con el nombre de producto, precio y nombre de fabricante, de todos los productos que tengan un precio mayor o igual a 180€. Ordene el resultado en primer lugar por el precio (en orden descendente) y en segundo lugar por el nombre (en orden ascendente)
-- Devuelve un listado con el código y el nombre de fabricante, solamente de aquellos fabricantes que tienen productos asociados en la base de datos.
-- Devuelve un listado de todos los fabricantes que existen en la base de datos, junto con los productos que tiene cada uno de ellos. El listado deberá mostrar también aquellos fabricantes que no tienen productos asociados.
-- Devuelve un listado donde sólo aparezcan aquellos fabricantes que no tienen ningún producto asociado.
-- Calcula el número total de productos que hay en la tabla productos.
-- Calcula el número total de fabricantes que hay en la tabla fabricante.
-- Calcula el número de valores distintos de código de fabricante aparecen en la tabla productos.
-- Calcula la media del precio de todos los productos.
-- Calcula el precio más barato de todos los productos.
-- Calcula el precio más caro de todos los productos.
-- Lista el nombre y el precio del producto más barato.
-- Lista el nombre y el precio del producto más caro.
-- Calcula la suma de los precios de todos los productos.
-- Calcula el número de productos que tiene el fabricante Asus.
-- Calcula la media del precio de todos los productos del fabricante Asus.
-- Calcula el precio más barato de todos los productos del fabricante Asus.
-- Calcula el precio más caro de todos los productos del fabricante Asus.
-- Calcula la suma de todos los productos del fabricante Asus.
-- Muestra el precio máximo, precio mínimo, precio medio y el número total de productos que tiene el fabricante Crucial.
-- Muestra el número total de productos que tiene cada uno de los fabricantes. El listado también debe incluir los fabricantes que no tienen ningún producto. El resultado mostrará dos columnas, una con el nombre del fabricante y otra con el número de productos que tiene. Ordene el resultado descendentemente por el número de productos.
-- Muestra el precio máximo, precio mínimo y precio medio de los productos de cada uno de los fabricantes. El resultado mostrará el nombre del fabricante junto con los datos que se solicitan.
-- Muestra el precio máximo, precio mínimo, precio medio y el número total de productos de los fabricantes que tienen un precio medio superior a 200€. No es necesario mostrar el nombre del fabricante, con el código del fabricante es suficiente.
-- Muestra el nombre de cada fabricante, junto con el precio máximo, precio mínimo, precio medio y el número total de productos de los fabricantes que tienen un precio medio superior a 200€. Es necesario mostrar el nombre del fabricante.
-- Calcula el número de productos que tienen un precio mayor o igual a 180€.
-- Calcula el número de productos que tiene cada fabricante con un precio mayor o igual a 180€.
-- Lista el precio medio los productos de cada fabricante, mostrando solamente el código del fabricante.
-- Lista el precio medio los productos de cada fabricante, mostrando solamente el nombre del fabricante.
-- Lista los nombres de los fabricantes cuyos productos tienen un precio medio mayor o igual a 150€.
-- Devuelve un listado con los nombres de los fabricantes que tienen 2 o más productos.
-- Devuelve un listado con los nombres de los fabricantes y el número de productos que tiene cada uno con un precio superior o igual a 220 €. No es necesario mostrar el nombre de los fabricantes que no tienen productos que cumplan la condición.

